
import __ASTRO_IMAGE_IMPORT_Z1OqrBX from "./easy-meatloaf-step-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2FEasy-Meatloaf-Recipe-Delicious%26Simple%2FEasy-Meatloaf-Recipe-Delicious-Simple.md";
import __ASTRO_IMAGE_IMPORT_2sXWlT from "./easy-meatloaf-step-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2FEasy-Meatloaf-Recipe-Delicious%26Simple%2FEasy-Meatloaf-Recipe-Delicious-Simple.md";
import __ASTRO_IMAGE_IMPORT_2h08vE from "./easy-christmas-cracker-candy-recipe-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Feasy-christmas-cracker-candy-recipe%2Feasy-christmas-cracker-candy-recipe.md";
import __ASTRO_IMAGE_IMPORT_Z1gq9z from "./easy-christmas-cracker-candy-recipe-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Feasy-christmas-cracker-candy-recipe%2Feasy-christmas-cracker-candy-recipe.md";
import __ASTRO_IMAGE_IMPORT_Z2jwYON from "./easy-christmas-cracker-candy-recipe-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Feasy-christmas-cracker-candy-recipe%2Feasy-christmas-cracker-candy-recipe.md";
import __ASTRO_IMAGE_IMPORT_6AXgb from "./the-best-christmas-cracker-candy-recipe-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fthe-best-christmas-cracker-candy-recipe%2Fthe-best-christmas-cracker-candy-recipe.md";
import __ASTRO_IMAGE_IMPORT_Z2W04x from "./the-best-christmas-cracker-candy-recipe-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fthe-best-christmas-cracker-candy-recipe%2Fthe-best-christmas-cracker-candy-recipe.md";
import __ASTRO_IMAGE_IMPORT_ZcuXpg from "./the-best-christmas-cracker-candy-recipe-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fthe-best-christmas-cracker-candy-recipe%2Fthe-best-christmas-cracker-candy-recipe.md";
export default new Map([["./easy-meatloaf-step-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2FEasy-Meatloaf-Recipe-Delicious%26Simple%2FEasy-Meatloaf-Recipe-Delicious-Simple.md", __ASTRO_IMAGE_IMPORT_Z1OqrBX], ["./easy-meatloaf-step-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2FEasy-Meatloaf-Recipe-Delicious%26Simple%2FEasy-Meatloaf-Recipe-Delicious-Simple.md", __ASTRO_IMAGE_IMPORT_2sXWlT], ["./easy-christmas-cracker-candy-recipe-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Feasy-christmas-cracker-candy-recipe%2Feasy-christmas-cracker-candy-recipe.md", __ASTRO_IMAGE_IMPORT_2h08vE], ["./easy-christmas-cracker-candy-recipe-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Feasy-christmas-cracker-candy-recipe%2Feasy-christmas-cracker-candy-recipe.md", __ASTRO_IMAGE_IMPORT_Z1gq9z], ["./easy-christmas-cracker-candy-recipe-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Feasy-christmas-cracker-candy-recipe%2Feasy-christmas-cracker-candy-recipe.md", __ASTRO_IMAGE_IMPORT_Z2jwYON], ["./the-best-christmas-cracker-candy-recipe-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fthe-best-christmas-cracker-candy-recipe%2Fthe-best-christmas-cracker-candy-recipe.md", __ASTRO_IMAGE_IMPORT_6AXgb], ["./the-best-christmas-cracker-candy-recipe-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fthe-best-christmas-cracker-candy-recipe%2Fthe-best-christmas-cracker-candy-recipe.md", __ASTRO_IMAGE_IMPORT_Z2W04x], ["./the-best-christmas-cracker-candy-recipe-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Frecipes%2Fthe-best-christmas-cracker-candy-recipe%2Fthe-best-christmas-cracker-candy-recipe.md", __ASTRO_IMAGE_IMPORT_ZcuXpg]]);
		